### ISSUE TITLE
improving PKGBUILD

### ISSUE THREAD

**Issue by ghost** [Arthurdw/statusof#2]
I noticed this being added to the [AUR](https://aur.archlinux.org/packages/python-statusof) and decided to try it out. Using `pip` to install isn't at all common for python packages and is advised against in the [package guidelines](https://wiki.archlinux.org/title/Python_package_guidelines#Installation_methods). As is the PKGBUILD fails to add missing depends `python-aiohttp` and `python-colorama`.

Seeing the project already has a setup.py file,it would be easy to use that in the PKGBUILD. The only thing that would make this easier for Arch Linux users to install is tagging releases as you go along. Below is an example, using the current latest commit instead of a tagged release.

```
# Maintainer: Arthurdw <contact@arthurdw.com>
_name=statusof
pkgname=python-${_name}
pkgver=0.2.2
pkgrel=1
pkgdesc="Small Python script to check the status of a list of URLs."
arch=(x86_64 i686)
url="https://github.com/Arthurdw/statusof"
license=('MIT')
depends=('python-aiohttp' 'python-colorama')
makedepends=('git' 'python-setuptools')
optdepends=('python-aiodns: for fast DNS resolving')
_commit=904e3a53c04a26e2a7d3420cffccfcad3a756af1
source=("git+https://github.com/Arthurdw/statusof.git#commit=${_commit}")
sha256sums=('SKIP')

build() {
    cd "$_name"

    python setup.py build
}

package() {
    cd "$_name"

    python setup.py install --root="$pkgdir" --skip-build --optimize=1
}
```

HTH, regards

**Comment by Arthurdw** [comment]
Thank you SO much! This is my first AUR package, so thank you for lmk.  
Your solution is getting used in the new publishes! ♥

Tagged releases on git won't be a thing for this pkg tho. As I do not expect to have the need to properly version manage this beyond just a simple string.
